spring:
  datasource:
    # database in-memory for tests
    url: jdbc:h2:mem:testdb

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

application:
  #configuring external calls
  poke-api:
    url: https://pokeapi.co/api/v2/